apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: hz-proxy-pass
  namespace: default
spec:
  virtualhost:
    fqdn: 146.220.66.34.bc.googleusercontent.com
    tls:
      passthrough: true
  tcpproxy:
    services:
      - name: hazelcast
        port: 11010